"""Noba – Report generation for periodic email summaries and custom templates."""
from __future__ import annotations

import logging
import time
from datetime import datetime, timezone

logger = logging.getLogger("noba")


def generate_system_report(db_instance, range_hours: int = 168) -> dict:
    """Generate a system report covering the specified time range."""
    now = int(time.time())
    cutoff = now - range_hours * 3600

    # Collect metrics summaries
    metrics = {}
    for metric in ("cpu_percent", "mem_percent", "cpu_temp"):
        points = db_instance.get_history(metric, range_hours=range_hours, resolution=3600)
        if points:
            values = [p["value"] for p in points]
            metrics[metric] = {
                "avg": round(sum(values) / len(values), 1),
                "max": round(max(values), 1),
                "min": round(min(values), 1),
                "points": len(values),
            }

    # Collect alert history
    alerts = db_instance.get_alert_history(limit=50, from_ts=cutoff)

    # Collect job run stats
    stats = db_instance.get_automation_stats()

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "range_hours": range_hours,
        "metrics": metrics,
        "alert_count": len(alerts),
        "alerts": alerts[:10],
        "automation_stats": stats,
    }


def render_html_report(report: dict) -> str:
    """Render a report dict as HTML for email."""
    metrics = report.get("metrics", {})
    generated = report.get("generated_at", "")
    range_h = report.get("range_hours", 168)
    alert_count = report.get("alert_count", 0)

    rows = []
    for metric, data in metrics.items():
        label = metric.replace("_", " ").title()
        rows.append(
            f"<tr><td>{label}</td>"
            f"<td>{data['avg']}</td>"
            f"<td>{data['max']}</td>"
            f"<td>{data['min']}</td></tr>"
        )

    stats = report.get("automation_stats", {})
    auto_rows = []
    for auto_id, s in stats.items():
        auto_rows.append(
            f"<tr><td>{auto_id}</td>"
            f"<td>{s.get('total', 0)}</td>"
            f"<td>{s.get('ok', 0)}</td>"
            f"<td>{s.get('fail', 0)}</td></tr>"
        )

    return f"""<!DOCTYPE html>
<html>
<head><style>
body {{ font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }}
table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
th {{ background: #333; color: white; }}
h2 {{ color: #333; border-bottom: 2px solid #007bff; padding-bottom: 5px; }}
.stat {{ display: inline-block; padding: 5px 15px; margin: 5px; background: #f0f0f0; border-radius: 5px; }}
</style></head>
<body>
<h1>NOBA System Report</h1>
<p>Generated: {generated} | Range: {range_h}h | Alerts: {alert_count}</p>

<h2>System Metrics</h2>
<table>
<tr><th>Metric</th><th>Avg</th><th>Max</th><th>Min</th></tr>
{''.join(rows) if rows else '<tr><td colspan="4">No data</td></tr>'}
</table>

<h2>Automation Stats</h2>
<table>
<tr><th>Automation</th><th>Total</th><th>OK</th><th>Failed</th></tr>
{''.join(auto_rows) if auto_rows else '<tr><td colspan="4">No data</td></tr>'}
</table>

<p style="color: #999; font-size: 12px;">Generated by NOBA Command Center</p>
</body>
</html>"""


def send_periodic_report(db_instance, read_settings_fn, range_hours: int = 168) -> bool:
    """Generate and send a periodic email report."""
    cfg = read_settings_fn()
    notif_cfg = cfg.get("notifications", {})
    email_cfg = notif_cfg.get("email", {})
    if not email_cfg.get("enabled"):
        return False

    report = generate_system_report(db_instance, range_hours)
    html = render_html_report(report)

    try:
        import smtplib
        from email.message import EmailMessage
        smtp = email_cfg.get("smtp_server", "")
        user = email_cfg.get("username", "")
        passwd = email_cfg.get("password", "")
        from_a = email_cfg.get("from", "")
        to_a = email_cfg.get("to", "")
        if smtp and user and passwd and from_a and to_a:
            em = EmailMessage()
            em.set_content(f"NOBA System Report — {report.get('range_hours', 168)}h summary")
            em.add_alternative(html, subtype="html")
            em["Subject"] = f"NOBA Weekly Report — {datetime.now().strftime('%Y-%m-%d')}"
            em["From"] = from_a
            em["To"] = to_a
            with smtplib.SMTP(smtp) as s:
                if email_cfg.get("starttls"):
                    s.starttls()
                s.login(user, passwd)
                s.send_message(em)
            logger.info("Periodic report sent to %s", to_a)
            return True
    except Exception as e:
        logger.error("Periodic report failed: %s", e)
    return False
